language: python
services:
  - docker

branches:
  only:
  - master
  - /\d+\.\d+/
  - /\d+\.\d+\.\d+/

env:
  - BOTO_CONFIG=/dev/null

script:
# build
- bash build_scripts/freeze_requirements.sh
- bash build_scripts/build_package.sh
# dry run
- pip install --no-cache-dir dist/ops*.tar.gz && ops --verbose -h
# Output something every 5 minutes or Travis kills the job
- while sleep 5m; do echo "=====[ $SECONDS seconds still running ]====="; done &
# build docker image
- docker build -f build_scripts/Dockerfile -t ops .
# Killing background sleep loop
- kill %1

before_deploy:
  - git add requirements.txt
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: "$GITHUB_API_KEY"
    file_glob: true
    file: "dist/**/*"
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash build_scripts/docker_push.sh
    on:
      tags: true
  
